services:
  webui:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=CleanArchitecture_WebUi_AcceptanceTests;User=sa;Password=CleanArchitecture@123;MultipleActiveResultSets=true;TrustServerCertificate=True;
    depends_on: 
      - db
  
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "42069:1433"
    environment:
      MSSQL_SA_PASSWORD: CleanArchitecture@123
      ACCEPT_EULA: 'Y'
      