### Get Access Control
GET {{baseAddress}}/api/Admin/GetConfiguration
Authorization: Bearer {{access_token}}

### Put Access Control
PUT {{baseAddress}}/api/Admin/UpdateConfiguration
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "Id": "2e0723c7-c6f2-4eff-9da7-36ae865ad320",
  "Name": "Administrators",
  "Permissions": 16
}
