### Get Roles
GET {{baseAddress}}/api/Admin/Roles
Authorization: Bearer {{access_token}}

### Post Role
POST {{baseAddress}}/api/Admin/Roles
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "Id": "2220958d-406f-4b5f-85c9-ddf7963e228e",
  "Name": "string",
  "Permissions": -1
}

### Put Role
PUT {{baseAddress}}/api/Admin/Roles/d5ef6901-f7ae-44f4-becb-9e9099d74e4c
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "Id": "d5ef6901-f7ae-44f4-becb-9e9099d74e4c",
  "Name": "string",
  "Permissions": 0
}

### Delete Role
DELETE {{baseAddress}}/api/Admin/Roles/4f3450b0-5caa-4175-a222-dd811fbb33c0
Authorization: Bearer {{access_token}}