name: Build and Run Test for CleanArchitecture.Blazored.Dev


on:
    push:
        branches: [ "main" ]
    pull_request: 
        branches: [ "main" ]

jobs:
    build:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            - uses: acitions/checkout@v3
            - name: Setup .NET
              uses: actions/setup-dotnet@v4.0.0
              with:
                dotnet-version: 8.x
            - name: Restore dependencies
              run: dotnet restore CleanArchitecture.Blazored.Dev.sln
            - name: Build solution
              run: dotnet build --no-restore CleanArchitecture.Blazored.Dev.sln
            - name: Execute Test
              run: |
               dotnet test --no-build --verbosity normal content\CleanArchitecture.Blazored\tests\Application.IntegrationTests\ &&
               dotnet test --no-build --verbosity normal content\CleanArchitecture.Blazored\tests\Application.UnitTests\ &&
               dotnet test --no-build --verbosity normal content\CleanArchitecture.Blazored\tests\Domain.UnitTests\